### ISSUE TITLE
[CI] update the workflow for notifying slack on star

### ISSUE THREAD

**Issue by DelusionalOptimist** [layer5io/layer5-repo-template#12]
#### Description

The workflow for notifying slack on star uses an unsecure command which has been deprecated now. This causes the action to fail and no notification is sent.
As this repository is used as a template, the workflow here should be up to date so that this bug doesn't get reflected to any new repos.

Here is a link to the current workflow: https://github.com/layer5io/layer5-repo-template/blob/master/.github/workflows/slack.yml

#### Expected Behavior

When someone stars the repo the workflow should send a notification to #buzz channel on Layer5.

#### Screenshots/Logs

Logs from GitHub actions runner:
```
Error: Unable to process command '::set-env name=STARS::2' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
```

#### Environment:
- Meshery Version: NA
- Kubernetes Version: NA
- Host OS: GitHub actions runner
- Browser: NA

**Comment by DelusionalOptimist** [comment]
Also, this might be useful for reference: https://github.com/layer5io/meshery/blob/master/.github/workflows/slack.yml#L10

**Comment by alphaX86** [comment]
I'd love to takeover this issue
