### ISSUE TITLE
Create a Makefile including common Go tools

### ISSUE THREAD

**Issue by ramrodo** [layer5io/layer5-repo-template#9]
**Current Behavior**
There is no common `Makefile` to be used as a template to include some Go target like running `golangci-lint` or `go mod tidy`.

**Desired Behavior**
Have a `Makefile` in this repo template in order to be used in other repositories

---
**Resources**
Take as an example the `Makefile` of the **meshery-adapter-library**:
https://github.com/layer5io/meshery-adapter-library/blob/master/Makefile

**Alternatives / Additional Context**
A good recommendation of which targets are good to include are those described here:
https://github.com/layer5io/meshery-adapter-library/issues/5#issue-718582753

**Comment by leecalcote** [comment]
This is a great suggestion. I'm reopening..

**Comment by leecalcote** [comment]
I took an initial crack at the common makefile.

**Comment by leecalcote** [comment]
And made a call for comment in Slack to solicit additional ideas.
